### PR TITLE
use apiRequester class

### PR DESCRIPTION
**Pull request by ah7255703**

### CODE REVIEW

**Review by codebanesr — APPROVED** [review]

**Comment by codebanesr** [comment]
@ah7255703 please confirm that the tests are passing, and also don't use fork, you are in the organization 😄

**Comment by ah7255703** [comment]
> @ah7255703 please confirm that the tests are passing, and also don't use fork, you are in the organization 😄 

It refused to push 😞, yes bro the tests were passed

**Comment by codebanesr** [comment]
Two failing, will fix and push
  1) Copilot Integration Tests
       should create a flow:

      AssertionError: expected { status: 201, …(5) } to have keys 'blocks', 'description', 'flow_id', 'last_saved_at', and 'name'
      + expected - actual

       [
      -  "config"
      -  "data"
      -  "headers"
      -  "request"
      -  "status"
      -  "statusText"
      +  "blocks"
      +  "description"
      +  "flow_id"
      +  "last_saved_at"
      +  "name"
       ]
      
      at Context.<anonymous> (test/action.test.ts:75:31)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

  2) Copilot Integration Tests
       should fetch all flows for the bot by bot id:
     AssertionError: expected { status: 200, statusText: 'OK', …(4) } to be an array
      at Context.<anonymous> (test/action.test.ts:81:29)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by codebanesr** [comment]
make sure to return `result.data` from axios call
```
  public async getAllFlowsByBotId(botId: string) {
    const url = `${this.backendBase}/flows/bot/${botId}`;
    const result = await this.i.get<Flow[]>(url);

    return result.data
  }
  ```

**Pull request merged**
